POST http://localhost:8081/api/auth/register 
content-type: application/json

{
  "nome": "admin",
  "email": "admin@email.com",
  "senha": "123456",
  "role": "ADMIN"
}

###

POST http://localhost:8081/api/auth/login
content-type: application/json

{
  "email": "andre@email.com",
  "senha": "123456"
}

###

POST http://localhost:8081/api/auth/login
content-type: application/json

{
  "email": "admin@email.com",
  "senha": "123456"
}

###

GET http://localhost:8081/api/auth/admin/area
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbmRyZUBlbWFpbC5jb20iLCJyb2xlIjoiVVNFUiIsImlhdCI6MTc0NjgxNzkwMiwiZXhwIjoxNzQ2ODIxNTAyfQ.u_Sk0O3oVcokl9BKASdjVAZPPMT9CHH_xdzVPmjbOjQ

###

GET http://localhost:8081/api/cliente/dados
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBlbWFpbC5jb20iLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NDY4MjA2NjksImV4cCI6MTc0NjgyNDI2OX0.K92txM2MTAjntF5PrEluNi5DDQmA0rhrovQC7DTYHbc
###

GET http://localhost:8081/api/admin/clientes
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBlbWFpbC5jb20iLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NDY4MjE0ODAsImV4cCI6MTc0NjgyNTA4MH0.IP0D_2Q2uNsORRzbgJxpfalGR---5K5939ZK-Vjy2QY

###

PUT http://localhost:8081/api/cliente/nome
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbmRyZUBlbWFpbC5jb20iLCJyb2xlIjoiVVNFUiIsImlhdCI6MTc0NjgyNDkxOSwiZXhwIjoxNzQ2ODI4NTE5fQ.AcurYTULjIJIjspqwllBa1RdwrzuKgncut8caC5cOdE
Content-Type: application/json

{
  "nome": "Andre SNas"
}